export const ROLE_CATEGORIES = [
  "Data Scientist",
  "ML Engineer",
  "Data Analyst",
  "AI Engineer",
  "Data Engineer",
  "Analytics Manager",
  "MLOps Engineer",
  "NLP Specialist",
  "Research Scientist",
  "BI Analyst",
  "AI Product Manager",
  "Other",
];

export const DEFAULT_ROLES = [
  "Data Scientist",
  "Data Analyst",
  "Data Engineer",
  "BI Analyst",
  "Analytics Manager",
];

export const SENIORITY_LEVELS = [
  "Junior",
  "Mid",
  "Senior",
  "Lead",
  "Principal",
  "Director",
];

export const WORK_MODES = ["Remote", "Hybrid", "Onsite", "Unknown"];

export const AI_INVOLVEMENT_LEVELS = {
  "Uses AI to augment": ["AI Literacy & Augmentation", "Prompt Engineering"],
  "Uses ML models": ["Classical ML", "Deep Learning", "NLP", "Computer Vision"],
  "AI/LLM Engineering": [
    "LLM & GenAI Development",
    "AI Agents & Automation",
    "AI Evaluation & Safety",
    "Responsible AI & Governance",
  ],
  "MLOps & Infrastructure": ["MLOps & Infrastructure"],
} as const;

export const SKILL_TIERS = {
  "Tier 1: Foundational": [
    "AI Literacy & Augmentation",
    "Prompt Engineering",
  ],
  "Tier 2: Professional": [
    "Classical ML",
    "Deep Learning",
    "NLP",
    "MLOps & Infrastructure",
    "LLM & GenAI Development",
  ],
  "Tier 3: Specialist": [
    "AI Agents & Automation",
    "AI Evaluation & Safety",
    "Computer Vision",
    "Responsible AI & Governance",
  ],
} as const;

export const AI_SKILLS_TAXONOMY: Record<string, string[]> = {
  "AI Literacy & Augmentation": [
    "ai tools",
    "ai-powered",
    "chatgpt",
    "microsoft copilot",
    "github copilot",
    "claude",
    "gemini",
    "generative ai tools",
    "ai productivity",
    "leverage ai",
    "copilot",
  ],
  "Prompt Engineering": [
    "prompt engineering",
    "prompt design",
    "few-shot",
    "chain of thought",
    "system prompts",
    "prompt templates",
    "prompt tuning",
    "prompt injection",
  ],
  "LLM & GenAI Development": [
    "llm",
    "large language model",
    "foundation model",
    "rag",
    "retrieval augmented generation",
    "vector database",
    "pinecone",
    "embeddings",
    "fine-tuning",
    "langchain",
    "llamaindex",
    "openai api",
    "hugging face",
    "generative ai",
    "genai",
  ],
  "AI Agents & Automation": [
    "ai agent",
    "agentic",
    "autonomous agent",
    "multi-agent",
    "tool calling",
    "function calling",
    "autogen",
    "crewai",
    "langgraph",
    "model context protocol",
    "mcp",
  ],
  "AI Evaluation & Safety": [
    "model evaluation",
    "evals",
    "red teaming",
    "ai safety",
    "guardrails",
    "benchmark",
    "rlhf",
    "alignment",
    "model risk",
  ],
  "Classical ML": [
    "machine learning",
    "scikit-learn",
    "sklearn",
    "xgboost",
    "feature engineering",
    "regression",
    "classification",
    "clustering",
    "forecasting",
    "anomaly detection",
  ],
  "Deep Learning": [
    "deep learning",
    "neural network",
    "pytorch",
    "tensorflow",
    "keras",
    "jax",
    "cnn",
    "lstm",
    "transformer",
    "gpu training",
  ],
  NLP: [
    "natural language processing",
    "nlp",
    "bert",
    "roberta",
    "text classification",
    "sentiment analysis",
    "named entity recognition",
    "document processing",
    "spacy",
    "nltk",
  ],
  "Computer Vision": [
    "computer vision",
    "image classification",
    "object detection",
    "yolo",
    "ocr",
    "opencv",
    "video analysis",
    "facial recognition",
    "medical imaging",
  ],
  "MLOps & Infrastructure": [
    "mlops",
    "machine learning operations",
    "model deployment",
    "model serving",
    "model monitoring",
    "mlflow",
    "kubeflow",
    "model registry",
    "feature store",
    "sagemaker",
    "vertex ai",
    "azure ml",
    "llmops",
  ],
  "Responsible AI & Governance": [
    "responsible ai",
    "ethical ai",
    "ai governance",
    "ai policy",
    "ai regulation",
    "ai compliance",
    "explainable ai",
    "xai",
    "fairness",
    "bias mitigation",
    "model card",
  ],
};

export const ROLE_COLORS = [
  "#2dd4bf",
  "#f59e0b",
  "#60a5fa",
  "#fb7185",
  "#a78bfa",
  "#34d399",
  "#f97316",
  "#22d3ee",
  "#e879f9",
  "#84cc16",
  "#f43f5e",
];
